
import { UserProfile, ServerOption, AppLanguage, Notification } from './types';

export const ANIRIAS_RED = '#E50914';
export const ANIRIAS_DARK = '#141414';

export const DXD_AVATARS = [
    { name: 'Rias Gremory', url: 'https://picsum.photos/seed/riasgremory/200' },
    { name: 'Issei Hyoudou', url: 'https://picsum.photos/seed/isseidragon/200' },
    { name: 'Akeno Himejima', url: 'https://picsum.photos/seed/akeno/200' },
    { name: 'Koneko Toujou', url: 'https://picsum.photos/seed/koneko/200' },
    { name: 'Asia Argento', url: 'https://picsum.photos/seed/asia/200' },
    { name: 'Xenovia Quarta', url: 'https://picsum.photos/seed/xenovia/200' },
    { name: 'Gasperp Vladi', url: 'https://picsum.photos/seed/gasper/200' },
    { name: 'Vali Lucifer', url: 'https://picsum.photos/seed/vali/200' },
];

// FIX: Export `SERVERS` to resolve import error in `VideoPlayer.tsx`.
export const SERVERS: ServerOption[] = [
    { id: 'alpha', name: 'Alpha', quality: '1080p' },
    { id: 'beta', name: 'Beta', quality: '720p' },
    { id: 'gamma', name: 'Gamma', quality: '480p' },
];

// FIX: Export `INITIAL_PROFILES` to resolve import error in `store.ts`.
export const INITIAL_PROFILES: UserProfile[] = [
    { id: '1', name: 'Rias', avatar: DXD_AVATARS[0].url, isKid: false, language: 'en', autoplayNext: true, autoplayPreviews: true },
    { id: '2', name: 'Issei', avatar: DXD_AVATARS[1].url, isKid: false, language: 'en', autoplayNext: true, autoplayPreviews: false },
    { id: '3', name: 'Akeno', avatar: DXD_AVATARS[2].url, isKid: false, language: 'en', autoplayNext: true, autoplayPreviews: true },
    { id: '4', name: 'Koneko', avatar: DXD_AVATARS[3].url, isKid: true, language: 'en', autoplayNext: false, autoplayPreviews: false },
];

// FIX: Export `MOCK_NOTIFICATIONS` to resolve import error in `store.ts`.
export const MOCK_NOTIFICATIONS: Notification[] = [
    {
        id: '1',
        animeId: 'jujutsu-kaisen',
        title: "New Episode: Jujutsu Kaisen",
        message: "Season 2 Episode 18 'Right and Wrong' is now available.",
        image: "https://picsum.photos/seed/jjk/200",
        time: "2 hours ago",
        read: false
    },
    {
        id: '2',
        animeId: 'high-school-dxd',
        title: "High School DxD Season 5 Announcement",
        message: "A new season has been officially announced for 2025!",
        image: "https://picsum.photos/seed/dxd/200",
        time: "1 day ago",
        read: false
    },
    {
        id: '3',
        animeId: 'one-punch-man',
        title: "One Punch Man S3 Trailer",
        message: "The first trailer for the highly anticipated third season has dropped.",
        image: "https://picsum.photos/seed/opm/200",
        time: "3 days ago",
        read: true
    }
];

export const TRANSLATIONS: Record<AppLanguage, any> = {
  tr: {
    home: "Ana Sayfa",
    latestEpisodes: "Yeni Bölümler",
    calendar: "Takvim",
    archive: "Anime Arşiv",
    myList: "Listem",
    adminPanel: "Yönetici Paneli",
    browseLanguages: "Dillere Göre Göz At",
    searchPlaceholder: "Anime ara...",
    play: "Oynat",
    moreInfo: "Daha Fazla Bilgi",
    match: "Eşleşme",
    episode: "Bölüm",
    episodes: "Bölümler",
    moreLikeThis: "Benzer İçerikler",
    server: "Sunucu",
    skipIntro: "İntroyu Atla",
    continueWatching: "İzlemeye Devam Et",
    trending: "Gündemdekiler",
    becauseWatched: "Bunu izlediğin için:",
    exploreAll: "Hepsini Keşfet",
    account: "Hesap",
    helpCenter: "Yardım Merkezi",
    signOut: "Çıkış Yap",
    switchProfile: "Profil Değiştir",
    whosWatching: "Kim izliyor?",
    addProfile: "Profil Ekle",
    manageProfiles: "Profilleri Yönet",
    editProfile: "Profili Düzenle",
    deleteProfile: "Profili Sil",
    done: "Tamam",
    save: "Kaydet",
    cancel: "İptal",
    name: "İsim",
    kidProfile: "Çocuk Profili?",
    emptyList: "Listeniz boş.",
    audioSubtitles: "Seslendirme ve Alt Yazı",
    privacy: "Gizlilik",
    terms: "Kullanım Koşulları",
    contact: "Bize Ulaşın",
    footerCopy: "© 2024 Anirias, Inc.",
    notifications: "Bildirimler",
    markAllRead: "Tümünü Okundu İşaretle",
    noNotifications: "Bildirim yok.",
    season: "Sezon",
    studio: "Stüdyo",
    airingTime: "Yayın Saati",
    sort: "Sıralama",
    categories: "Kategoriler",
    oracleGreeting: "Ben Anirias Kahini. Ruhun bugün ne arıyor?",
    oraclePlaceholder: "Bir öneri iste...",
    oracleTitle: "Anirias Kahini",
    sortBy: {
      newest: "En Yeni",
      oldest: "En Eski",
      az: "A-Z",
      za: "Z-A",
      rating: "Puana Göre"
    },
    adminManageAnime: "Anime Yönetimi",
    adminManageEpisodes: "Bölüm Yönetimi",
    adminAddAnime: "Yeni Anime Ekle",
    adminEditAnime: "Anime Düzenle",
    adminImportJikan: "Jikan/MAL'dan İçe Aktar",
    adminSearchPlaceholder: "Jikan veritabanında ara... (örn: Naruto)",
    adminFillForm: "Formu Otomatik Doldur",
    adminTitle: "Başlık",
    adminDesc: "Açıklama",
    adminThumbnail: "Küçük Resim URL",
    adminHero: "Kapak Görseli URL",
    adminYear: "Yıl",
    adminStatus: "Durum",
    adminRating: "Yaş Sınırı",
    adminTags: "Etiketler (virgül ile)",
    adminBroadcastDay: "Yayın Günü",
    adminAddBtn: "ANIME EKLE",
    adminUpdateBtn: "GÜNCELLE",
    adminCancelEdit: "Düzenlemeyi İptal Et",
    adminExisting: "Mevcut İçerik",
    adminSelectSeries: "Dizi Seçin",
    adminEpTitle: "Bölüm Başlığı",
    adminDuration: "Süre (saniye)",
    adminSeasonNum: "Sezon No",
    adminAddEpBtn: "BÖLÜM YÜKLE",
    adminUpdateEpBtn: "BÖLÜM GÜNCELLE",
    adminSeasonName: "Sezon İsmi (örn: 1. Sezon)",
    adminStudio: "Stüdyo",
    days: {
      Monday: "Pazartesi",
      Tuesday: "Salı",
      Wednesday: "Çarşamba",
      Thursday: "Perşembe",
      Friday: "Cuma",
      Saturday: "Cumartesi",
      Sunday: "Pazar"
    }
  },
  en: {
    home: "Home",
    latestEpisodes: "Latest Episodes",
    calendar: "Calendar",
    archive: "Archive",
    myList: "My List",
    adminPanel: "Admin Panel",
    browseLanguages: "Browse Languages",
    searchPlaceholder: "Search anime...",
    play: "Play",
    moreInfo: "More Info",
    match: "Match",
    episode: "Episode",
    episodes: "Episodes",
    moreLikeThis: "More Like This",
    server: "Server",
    skipIntro: "Skip Intro",
    continueWatching: "Continue Watching",
    trending: "Trending",
    becauseWatched: "Because you watched:",
    exploreAll: "Explore All",
    account: "Account",
    helpCenter: "Help Center",
    signOut: "Sign Out",
    switchProfile: "Switch Profile",
    whosWatching: "Who's watching?",
    addProfile: "Add Profile",
    manageProfiles: "Manage Profiles",
    editProfile: "Edit Profile",
    deleteProfile: "Delete Profile",
    done: "Done",
    save: "Save",
    cancel: "Cancel",
    name: "Name",
    kidProfile: "Kid Profile?",
    emptyList: "Your list is empty.",
    audioSubtitles: "Audio & Subtitles",
    privacy: "Privacy",
    terms: "Terms",
    contact: "Contact",
    footerCopy: "© 2024 Anirias, Inc.",
    notifications: "Notifications",
    markAllRead: "Mark All Read",
    noNotifications: "No notifications.",
    season: "Season",
    studio: "Studio",
    airingTime: "Airing Time",
    sort: "Sort By",
    categories: "Categories",
    oracleGreeting: "I am the Anirias Oracle. What does your soul seek today?",
    oraclePlaceholder: "Ask for a recommendation...",
    oracleTitle: "Oracle of Anirias",
    sortBy: {
      newest: "Newest",
      oldest: "Oldest",
      az: "A-Z",
      za: "Z-A",
      rating: "Rating"
    },
    adminManageAnime: "Manage Anime",
    adminManageEpisodes: "Manage Episodes",
    adminAddAnime: "Add New Anime",
    adminEditAnime: "Edit Anime",
    adminImportJikan: "Import from Jikan/MAL",
    adminSearchPlaceholder: "Search Jikan DB... (e.g. Naruto)",
    adminFillForm: "Auto-Fill Form",
    adminTitle: "Title",
    adminDesc: "Description",
    adminThumbnail: "Thumbnail URL",
    adminHero: "Hero Image URL",
    adminYear: "Year",
    adminStatus: "Status",
    adminRating: "Rating",
    adminTags: "Tags (comma separated)",
    adminBroadcastDay: "Broadcast Day",
    adminAddBtn: "ADD ANIME",
    adminUpdateBtn: "UPDATE ANIME",
    adminCancelEdit: "Cancel Edit",
    adminExisting: "Existing Content",
    adminSelectSeries: "Select Series",
    adminEpTitle: "Episode Title",
    adminDuration: "Duration (seconds)",
    adminSeasonNum: "Season No",
    adminAddEpBtn: "UPLOAD EPISODE",
    // FIX: Fix shorthand property error and complete truncated object.
    adminUpdateEpBtn: "UPDATE EPISODE",
    adminSeasonName: "Season Name (e.g. Season 1)",
    adminStudio: "Studio",
    days: {
      Monday: "Monday",
      Tuesday: "Tuesday",
      Wednesday: "Wednesday",
      Thursday: "Thursday",
      Friday: "Friday",
      Saturday: "Saturday",
      Sunday: "Sunday"
    }
  },
  // FIX: Add missing 'de' language object to satisfy the `Record<AppLanguage, any>` type.
  de: {
    home: "Startseite",
    latestEpisodes: "Neueste Episoden",
    calendar: "Kalender",
    archive: "Archiv",
    myList: "Meine Liste",
    adminPanel: "Admin-Panel",
    browseLanguages: "Sprachen durchsuchen",
    searchPlaceholder: "Anime suchen...",
    play: "Abspielen",
    moreInfo: "Mehr Infos",
    match: "Übereinstimmung",
    episode: "Episode",
    episodes: "Episoden",
    moreLikeThis: "Ähnliche Inhalte",
    server: "Server",
    skipIntro: "Intro überspringen",
    continueWatching: "Weiter ansehen",
    trending: "Trending",
    becauseWatched: "Weil du Folgendes gesehen hast:",
    exploreAll: "Alle entdecken",
    account: "Konto",
    helpCenter: "Hilfe-Center",
    signOut: "Abmelden",
    switchProfile: "Profil wechseln",
    whosWatching: "Wer schaut?",
    addProfile: "Profil hinzufügen",
    manageProfiles: "Profile verwalten",
    editProfile: "Profil bearbeiten",
    deleteProfile: "Profil löschen",
    done: "Fertig",
    save: "Speichern",
    cancel: "Abbrechen",
    name: "Name",
    kidProfile: "Kinderprofil?",
    emptyList: "Deine Liste ist leer.",
    audioSubtitles: "Audio & Untertitel",
    privacy: "Datenschutz",
    terms: "Nutzungsbedingungen",
    contact: "Kontakt",
    footerCopy: "© 2024 Anirias, Inc.",
    notifications: "Benachrichtigungen",
    markAllRead: "Alle als gelesen markieren",
    noNotifications: "Keine Benachrichtigungen.",
    season: "Staffel",
    studio: "Studio",
    airingTime: "Sendezeit",
    sort: "Sortieren nach",
    categories: "Kategorien",
    oracleGreeting: "Ich bin das Orakel von Anirias. Was sucht deine Seele heute?",
    oraclePlaceholder: "Frage nach einer Empfehlung...",
    oracleTitle: "Orakel von Anirias",
    sortBy: {
      newest: "Neueste",
      oldest: "Älteste",
      az: "A-Z",
      za: "Z-A",
      rating: "Bewertung"
    },
    adminManageAnime: "Anime verwalten",
    adminManageEpisodes: "Episoden verwalten",
    adminAddAnime: "Neuen Anime hinzufügen",
    adminEditAnime: "Anime bearbeiten",
    adminImportJikan: "Von Jikan/MAL importieren",
    adminSearchPlaceholder: "Jikan DB durchsuchen... (z.B. Naruto)",
    adminFillForm: "Formular automatisch ausfüllen",
    adminTitle: "Titel",
    adminDesc: "Beschreibung",
    adminThumbnail: "Thumbnail-URL",
    adminHero: "Hero-Image-URL",
    adminYear: "Jahr",
    adminStatus: "Status",
    adminRating: "Altersfreigabe",
    adminTags: "Tags (mit Komma getrennt)",
    adminBroadcastDay: "Sendetag",
    adminAddBtn: "ANIME HINZUFÜGEN",
    adminUpdateBtn: "ANIME AKTUALISIEREN",
    adminCancelEdit: "Bearbeitung abbrechen",
    adminExisting: "Vorhandener Inhalt",
    adminSelectSeries: "Serie auswählen",
    adminEpTitle: "Episodentitel",
    adminDuration: "Dauer (Sekunden)",
    adminSeasonNum: "Staffel-Nr.",
    adminAddEpBtn: "EPISODE HOCHLADEN",
    adminUpdateEpBtn: "EPISODE AKTUALISIEREN",
    adminSeasonName: "Staffelname (z.B. Staffel 1)",
    adminStudio: "Studio",
    days: {
      Monday: "Montag",
      Tuesday: "Dienstag",
      Wednesday: "Mittwoch",
      Thursday: "Donnerstag",
      Friday: "Freitag",
      Saturday: "Samstag",
      Sunday: "Sonntag"
    }
  }
};
